{% set name = "esdcan" %}
{% set version = "6.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/robotology/robotology-vcpkg-binary-ports/releases/download/storage/esdcan-${version}.zip
    sha256: 8a98b00df1dbb5a675c1d4554d3a277844fbfd7ce60df1f8b1f72ba92200cce0dd9bb833de158be223f1bdb47322486c5bfe57d60ec84e1a6822133627ed8e84

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

test:
  commands:
    - test -f ${PREFIX}/include/open62541/server.h  # [not win]
    - test -f ${PREFIX}/lib/libopen62541.so  # [linux]
    - test -f ${PREFIX}/lib/libopen62541.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/open62541/open62541Config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\open62541\\server.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\open62541.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\open62541.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\open62541\\open62541Config.cmake exit 1  # [win]

about:
  home: https://esd.eu/en/products/can-sdk
  summary: Software Development Kit (SDK) for esd NTCAN-API.

extra:
  recipe-maintainers:
    - traversaro
