{% set name = "esdcan" %}
{% set version = "6.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/robotology/robotology-vcpkg-binary-ports/releases/download/storage/esdcan-${version}.zip
    sha256: 8a98b00df1dbb5a675c1d4554d3a277844fbfd7ce60df1f8b1f72ba92200cce0dd9bb833de158be223f1bdb47322486c5bfe57d60ec84e1a6822133627ed8e84

build:
  number: 0
  skip: true  # [not win]
  # no run_exports as this package only contains a .lib 

test:
  commands:
    - if not exist %PREFIX%\\Library\\include\\ntcan.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\ntcan.lib exit 1  # [win]

about:
  home: https://esd.eu/en/products/can-sdk
  license_file: esd_license.txt
  summary: Software Development Kit (SDK) for esd NTCAN-API.

extra:
  recipe-maintainers:
    - traversaro
